name: oxedium_website
description: "Single-sided liquidity protocol"

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.0
  js: ^0.6.5
  solana: ^0.32.0
  flutter_svg: ^2.0.16
  fixnum: ^1.1.1
  http: ^1.3.0
  go_router: ^14.8.0
  adaptive_screen_flutter: ^0.0.5
  crypto: ^3.0.6
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  

  cupertino_icons: ^1.0.8

dependency_overrides:
  pinenacl: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.ttf
        - asset: assets/fonts/Aeonik-Bold.ttf
          weight: 700 
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
